=== Terms & Definitions

The following terms appear in this document and, when they do, the definitions in this section apply to them.

These terms are presented as a formal Semantic Web vocabulary at 

[id=backbone-model-defn]
Backbone Model::

`https://linked.data.gov.au/def/supermodel/terms/backbone-model[suterms:backbone-model]`
+
An integrative, summary model, that allows for crosswalking of elements within the Component Models of a Supermodel.

[id=background-model-defn]
Background Model::

`https://linked.data.gov.au/def/supermodel/terms/background-model[suterms:background-model]`
+
A standard and common Semantic Web model used as "upper" or higher order/abstract model for all other Supermodel models to conform to when modelling something within the Background Model's purview.

[id=central-class-defn]
Central Class::

`https://linked.data.gov.au/def/supermodel/terms/central-class[suterms:central-class]`
+
Central Classes are the generic data classes at the centre of Data Domains with high-level relationships between them defined in this supermodel. 
+
These classes are taken from general standards - usually well-known international standards - and specialised and extended within implementation scenarios to cater for specific needs.

[id=component-model-defn]
Component Model::

`https://linked.data.gov.au/def/supermodel/terms/component-model[suterms:component-model]`
+
An individual models of something of importance within a Supermodel scenario.

[id=data-domain-defn]
Data Domain::

`https://linked.data.gov.au/def/supermodel/terms/data-domain[suterms:data-domain]`
+
High-level conceptual areas within which Geosicence Australia has data. 
+
These Data Domains are not themed scientificly - 'geology', 'hydrogeology', etc. - but instead based on parts of the _Observations & Measurement_ <<ISO19156>> standard, realised in Semantic Web form in the SOSA Ontology, part of the _Semantic Sensor Network Ontology_ <<SSN>>.
+
Current Data Domain are shown in <<fig-top-level, Figure 1>>.

[id=fsdf-defn]
FSDF::

https://linked.data.gov.au/def/fsdf-supermodel#fsdf-defn[:fsdf-defn] - _defined here_
+
The Foundation Spatial Data Framework (FSDF): a project to deliver national coverages of the best available, most current, authoritative foundation data which is standardised and quality controlled. See https://link.fsdf.org.au.

[id=knowledge-graph-defn]
Knowledge Graph::

`https://linked.data.gov.au/def/supermodel/terms/knowledge-graph[suterms:knowledge-graph]`
+
A Knowledge Graph is a dataset that uses a graph data tructure - nodes and edges - with strongly-defined elements.

[id=linked-data-defn]
Linked Data::

`https://linked.data.gov.au/def/supermodel/terms/linked-data[suterms:linked-data]`
+
A set of technologies and conventions defined by the https://www.w3.org[World Wide Web Consortium] that aim to present data in both human- and machine-readable form over the Internet. 
+
Linked Data is strongly-defined with each element having either a local definition or a link to an available definition on the Internet.
+
Linked Data is graph-based in nature, that is it consistes of nodes and edges that can forever be linked to further conceps with defined relationships.
+
-- https://www.w3.org/standards/semanticweb/data

[id=location-index-defn]
Location Index::

`https://linked.data.gov.au/def/supermodel/terms/location-index[suterms:location-index]`
+
A project aiming to provide a consistent way to seamlessly integrate spatial data from distributed sources.
+
-- http://www.ga.gov.au/locationindex[Location Index Project Website]


[id=null-profile-defn]
Null Profile::

https://linked.data.gov.au/def/fsdf-supermodel#fsdf-defn[:mull-profile-defn] - _defined here_
+
A Null Profile is a Profile of a Standard that implements no additional constraints on the profile. A Null Profile's purpose is to act as a conformance target for the Standard by supplying itemised requrements and machine-executable validators when the Standard itself cannot have these elements added to it.


[id=ontology-defn]
Ontology::

`https://linked.data.gov.au/def/supermodel/terms/ontology[suterms:ontology]`
+
In computer science and information science, an ontology encompasses a representation, formal naming, and definition of the categories, properties, and relations between the concepts, data, and entities that substantiate one, many, or all domains of discourse.
+
The word ontology was originally defined as "the branch of philosophy that studies concepts such as existence, being, becoming, and reality". and the computer science term is derived from that definition.

[id=profile-defn]
Profile::
`https://www.w3.org/TR/dx-prof/#dfn-profile`
+
A data standard that constrains, extends, combines, or provides guidance or explanation about the usage of other standards.
+
This definition includes what are sometimes called "data profiles", "application profiles", "metadata application profiles", or "metadata profiles". In this document, "profile" and these other variants are all referred to as just "profiles".
+
NOTE: This definition has been taken from <<PROF>> and altered slightly for clarity here

[id=semantic-web-defn]
Semantic Web::

`https://linked.data.gov.au/def/supermodel/terms/semantic-web[suterms:semantic-web]`
+
The https://www.w3.org[World Wide Web Consortium]'s vision of an Internet-based web of Linked Data. 
+
Semantic Web is used to refer to something more than just the technologies and conventions of Linked Data; the term also encompases a specific set of interoperable data models - often called ontologies - published by the W3C, other standards bodies and some well-known companies.
+
The 'semantic' refers to the strongly-defined nature of the elements in the Semantic Web: the meaning of Semantic Web data is as precicely defined as any data can be.
+
-- https://www.w3.org/standards/semanticweb/

[id=vocabulary-defn]
Vocabulary::

`https://linked.data.gov.au/def/supermodel/terms/vocabulary[suterms:vocabulary]`
+
A managed codelist or taxonomy of concepts.
+
NOTE: Supermodels tend to use vocabularies formulated according to the <<SKOS>> taxonomy model or lists of objects defined using basic <<RDF>>, <<RDFS>> or <<OWL>> elements.
