=== Terms & Definitions

The following terms appear in this document and, when they do, the definitions in this section apply to them.

These terms are presented as a formal Semantic Web vocabulary at 

[id=central-class]
Central Class::

`https://linked.data.gov.au/def/supermodel-td/central-class[smtd:central-class]`
+
Central Classes are the generic data classes at the centre of Data Domains with high-level relationships between them defined in this supermodel. 
+
These classes are taken from general standards - usually well-known international standards - and specialised and extended within implementation scenarios to cater for specific needs.

[id=data-domain]
Data Domain::

`https://linked.data.gov.au/def/supermodel-td/data-domain[smtd:data-domain]`
+
High-level conceptual areas within which Geosicence Australia has data. 
+
These Data Domains are not themed scientificly - 'geology', 'hydrogeology', etc. - but instead based on parts of the _Observations & Measurement_ <<ISO19156>> standard, realised in Semantic Web form in the SOSA Ontology, part of the _Semantic Sensor Network Ontology_ <<SSN>>.
+
Current Data Domain are shown in <<fig-top-level, Figure 1>>.

[id=fsdf]
FSDF::

`https://linked.data.gov.au/def/supermodel-td/fsdf[smtd:fsdf]`
+
The Foundation Spatial Data Framework (FSDF): a project to deliver national coverages of the best available, most current, authoritative foundation data which is standardised and quality controlled. See https://link.fsdf.org.au.

[id=knowledge-graph]
Knowledge Graph::

`https://linked.data.gov.au/def/supermodel-td/knowledge-graph[smtd:knowledge-graph]`
+
A Knowledge Graph is a dataset that uses a graph data tructure - nodes and edges - with strongly-defined elements.

[id=linked-data]
Linked Data::

`https://linked.data.gov.au/def/supermodel-td/linked-data[smtd:linked-data]`
+
A set of technologies and conventions defined by the https://www.w3.org[World Wide Web Consortium] that aim to present data in both human- and machine-readable form over the Internet. 
+
Linked Data is strongly-defined with each element having either a local definition or a link to an available definition on the Internet.
+
Linked Data is graph-based in nature, that is it consistes of nodes and edges that can forever be linked to further conceps with defined relationships.
+
-- https://www.w3.org/standards/semanticweb/data

[id=location-index]
Location Index::

`https://linked.data.gov.au/def/supermodel-td/location-index[smtd:location-index]`
+
A project aiming to provide a consistent way to seamlessly integrate spatial data from distributed sources.
+
-- http://www.ga.gov.au/locationindex[Location Index Project Website]

[id=ontology]
Ontology::

`https://linked.data.gov.au/def/supermodel-td/ontology[smtd:ontology]`
+
In computer science and information science, an ontology encompasses a representation, formal naming, and definition of the categories, properties, and relations between the concepts, data, and entities that substantiate one, many, or all domains of discourse.
+
The word ontology was originally defined as "the branch of philosophy that studies concepts such as existence, being, becoming, and reality". and the computer science term is derived from that definition.

[id=semantic-web]
Semantic Web::

`https://linked.data.gov.au/def/supermodel-td/semantic-web[smtd:semantic-web]`
+
The https://www.w3.org[World Wide Web Consortium]'s vision of an Internet-based web of Linked Data. 
+
Semantic Web is used to refer to something more than just the technologies and conventions of Linked Data; the term also encompases a specific set of interoperable data models - often called ontologies - published by the W3C, other standards bodies and some well-known companies.
+
The 'semantic' refers to the strongly-defined nature of the elements in the Semantic Web: the meaning of Semantic Web data is as precicely defined as any data can be.
+
-- https://www.w3.org/standards/semanticweb/
