= FSDF Supermodel

This Model - the FSDF Supermodel - is the http://www.ga.gov.au/locationindex[Location Index (Loc-I) Projects]'s overarching data model that provides integration logic for all FSDF elements.

This work is part of a project to operationalise Loc-I for https://www.ga.gov.au[Geoscience Australia] initially undertaken by https://surroundaustralia.com[SURROUND Australia Pty Ltd].

== Specification document

This model's document is auto-built from source files within the FSDF Supermodel repository. Both the document and source files are viewable online.

The *Specification* document:

* https://geoscienceaustralia.github.io/fsdf-supermodel/supermodel.html

The *Repository*:

* https://github.com/geoscienceaustralia/fsdf-supermodel

The online and repository location will certainly change once this model is taken over by Geoscience Australia itself for continued use.

== License & Rights

The contents of this repository is licensed under Creative Commons 4.0 International. See the LICENSE file in the repository for details.

== Contacts

Official enquiries should be directed to:

**Geoscience Australia** +
GPO Box 378, Canberra ACT 2601 Australia +
<fsdf@ga.gov.au> +
General Enquiries: 1800 800 173, +
Switchboard: +61 2 6249 9111

Technical development of this work was undertaken by the following, for Geoscience Australia, so technical enquiries may be directed here:

**Nicholas J. Car** +
*Data Architect* +
initially of https://surroundaustralia.com[SURROUND Australia Pty Ltd.], +
currently of https://kurrawong.net[Kurrawong AI] +
<nick@kurrawong.net> +
+61477 560 177
