name: Auto-build HTML

on: 
  push: 
      branches:
          - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Build
      working-directory: ./
      run: |
        echo "installing asciidoctor"
        sudo apt-get install asciidoctor ruby -y
        echo "Making deployment dir - docs/"
        mkdir docs
        echo "Add README to docs/"
        asciidoctor README.adoc -o docs/index.html
        echo "Add supermodel to docs/"
        asciidoctor 01-supermodel.adoc -o docs/supermodel.html
        sed -i 's#img src="#img src="https://geoscienceaustralia.github.io/fsdf-supermodel/#' docs/supermodel.html
        echo "Add supermodel RDF to docs/"
        cp rdf/*.ttl docs/
        echo "Add images to docs/"
        cp -r img docs/
        echo "Add profile to docs/"
        cp backbone-model-profile/profile.ttl docs/backbone-model-profile.ttl
        cp backbone-model-profile/validator.ttl docs/backbone-model-validator.ttl
        cp backbone-model-profile/validator-compounded.ttl docs/backbone-model-validator-compounded.ttl
        asciidoctor backbone-model-profile/profile.adoc -o docs/backbone-model-profile.html
        asciidoctor backbone-model-profile/spec.adoc -o docs/backbone-model-spec.html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         BRANCH: gh-pages
         FOLDER: docs